
---

- hosts: all
  gather_facts: true
  vars:
    patchdir: /patching

  tasks:
 
     - name: Create a directory if it does not exist
       ansible.builtin.file:
        path: /patching
        state: directory
        mode: '0755'

     - name: Ansible Facts output
       ansible.builtin.copy:
         content: {{ansible_facts}}
         dest: {{patchdir}}/{{ansible_fqdn}}
       delegate_to: localhost
         
     - name: Execute the command in remote shell; stdout goes to the specified file on the remote
       ansible.builtin.shell: /usr/sbin/dmidecode -s system-product-name > {{patchdir}}/{{ansible_date_time.date}}.system-product-nameBP

     - name: Execute the command in remote shell; stdout goes to the specified file on the remote
       ansible.builtin.shell: lsb_release -dr > {{patchdir}}/{{ansible_date_time.date}}.lsbreleaseBP

     - name: Check if GLIBC Exists
       ansible.builtin.shell: rpm -q glibc > {{patchdir}}/{{ansible_date_time.date}}.system-product-nameBP

     - name: Openssl PKG Version
       ansible.builtin.shell: rpm -qa|grep -i openssl > {{patchdir}}/{{ansible_date_time.date}}.opensslBP

     - name: Capture Network Configuration
       ansible.builtin.shell: /usr/sbin/ifconfig -a > {{patchdir}}/{{ansible_date_time.date}}.ifconfigBP

     - name: Install current patches
       ansible.builtin.yum:
         name: '*'
         state: latest

#     - name: UUIDD Status
#       ansible.builtin.shell: /etc/init.d/uuidd status > {{patchdir}}/uuiddBP
     


