
---

- hosts: all
  gather_facts: false
  vars:
    patchdir: /patching

  tasks:
     - name: Install current patches
       ansible.builtin.yum:
         name: '*'
         state: latest


     - name: Create a directory if it does not exist
        ansible.builtin.file:
        path: /patching
        state: directory
        mode: '0755'
     - name: Execute the command in remote shell; stdout goes to the specified file on the remote
        ansible.builtin.shell: /usr/sbin/dmidecode -s system-product-name" > {{patchdir}}/$date/system-product-nameBP

     - name: Execute the command in remote shell; stdout goes to the specified file on the remote
        ansible.builtin.shell: lsb_release -dr" > {{patchdir}}/$date/lsbreleaseBP

     - name: Check if GLIBC Exists
        ansible.builtin.shell: rpm -q glibc" > {{patchdir}}/$date/system-product-nameBP

     - name: Openssl PKG Version
        ansible.builtin.shell: rpm -qa|grep -i openssl" > {{patchdir}}/$date/opensslBP

     - name: Openssl PKG Version
        ansible.builtin.shell: /sbin/ifconfig -a|grep -i bcast > {{patchdir}}/$date/ifconfigBP

     - name: UUIDD Status
        ansible.builtin.shell: /etc/init.d/uuidd status" > {{patchdir}}/{{ansible.date}}/uuiddBP
     


